'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {createClient} from '@supabase/supabase-js';

const url=process.env.NEXT_PUBLIC_SUPABASE_URL;
const key=process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;
const supabase=url&&key?createClient(url,key,{auth:{persistSession:true,detectSessionInUrl:true}}):null;
const blank={carrier:'',contact:'',phone:'',registration:'',location:'Oslo',date:'',time:'',vehicle_type:'Termo',direction:'Nord-Norge',comment:''};
const roleName=r=>({admin:'Admin',dispatcher:'Dispatcher',carrier:'Transportør'}[r]||r);
const formatDate=v=>{if(!v)return['Ikke angitt',''];const d=new Date(v);return[new Intl.DateTimeFormat('nb-NO',{dateStyle:'short'}).format(d),new Intl.DateTimeFormat('nb-NO',{timeStyle:'short'}).format(d)]};

export default function Page(){
 const[session,setSession]=useState(null),[profile,setProfile]=useState(null),[profiles,setProfiles]=useState([]),[rows,setRows]=useState([]),[view,setView]=useState('tower'),[q,setQ]=useState(''),[form,setForm]=useState(blank),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState('');
 const staff=profile?.approved&&['admin','dispatcher'].includes(profile.role),admin=profile?.approved&&profile.role==='admin';
 const ensureProfile=useCallback(async user=>{const{data,error}=await supabase.from('capacity_profiles').select('*').eq('user_id',user.id).maybeSingle();if(error)throw error;if(data)return data;const m=user.user_metadata||{};const created=await supabase.from('capacity_profiles').insert({user_id:user.id,email:user.email||m.email||'',full_name:m.full_name||m.name||user.email||'',company:m.company||'',role:'carrier',approved:false}).select().single();if(created.error)throw created.error;return created.data},[]);
 const loadVehicles=useCallback(async()=>{const{data,error}=await supabase.from('capacity_vehicles').select('*').order('available_at');if(error)throw error;setRows(data||[])},[]);
 const loadProfiles=useCallback(async()=>{const{data,error}=await supabase.from('capacity_profiles').select('*').order('created_at',{ascending:false});if(error)throw error;setProfiles(data||[])},[]);
 const boot=useCallback(async s=>{setLoading(true);setMessage('');try{if(!s?.user){setSession(null);setProfile(null);setRows([]);return}setSession(s);const p=await ensureProfile(s.user);setProfile(p);if(p.approved){await loadVehicles();if(['admin','dispatcher'].includes(p.role))await loadProfiles()}}catch(e){setMessage(e.message||'Kunne ikke laste systemet.')}finally{setLoading(false)}},[ensureProfile,loadProfiles,loadVehicles]);
 useEffect(()=>{if(!supabase){setLoading(false);return}supabase.auth.getSession().then(({data})=>boot(data.session));const{data}=supabase.auth.onAuthStateChange((_e,s)=>setTimeout(()=>boot(s),0));return()=>data.subscription.unsubscribe()},[boot]);
 useEffect(()=>{if(!supabase||!profile?.approved)return;const c=supabase.channel(`capacity-${session.user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'capacity_vehicles'},loadVehicles).subscribe();return()=>{supabase.removeChannel(c)}},[loadVehicles,profile?.approved,session?.user?.id]);
 const filtered=useMemo(()=>{const n=q.trim().toLowerCase();return n?rows.filter(r=>[r.carrier,r.contact,r.registration,r.location,r.vehicle_type,r.direction].some(v=>String(v||'').toLowerCase().includes(n))):rows},[rows,q]);
 async function login(){setMessage('');const{error}=await supabase.auth.signInWithOAuth({provider:'azure',options:{scopes:'email',redirectTo:window.location.origin}});if(error)setMessage(error.message)}
 async function logout(){await supabase.auth.signOut();setView('tower')}
 async function savePending(e){e.preventDefault();setSaving(true);const f=new FormData(e.currentTarget),{data,error}=await supabase.from('capacity_profiles').update({full_name:f.get('full_name'),company:f.get('company')}).eq('user_id',session.user.id).select().single();if(error)setMessage(error.message);else{setProfile(data);setMessage('Opplysningene er lagret. Du får tilgang når GNS har godkjent brukeren.')}setSaving(false)}
 async function submit(e){e.preventDefault();setSaving(true);setMessage('');const payload={owner_user_id:session.user.id,carrier:form.carrier.trim(),contact:form.contact.trim(),phone:form.phone.trim(),registration:form.registration.replace(/\s+/g,' ').trim().toUpperCase(),location:form.location.trim(),available_at:new Date(`${form.date}T${form.time}`).toISOString(),vehicle_type:form.vehicle_type,direction:form.direction.trim(),comment:form.comment.trim(),status:'Ledig',reserved_by:null,reserved_at:null};const{error}=await supabase.from('capacity_vehicles').insert(payload);if(error)setMessage(error.code==='23505'?'Denne bilen er allerede registrert.':error.message);else{await loadVehicles();setForm({...blank,carrier:form.carrier,contact:form.contact,phone:form.phone});setView('thanks')}setSaving(false)}
 async function reserve(r){if(!staff)return;const on=r.status==='Ledig';const{error}=await supabase.from('capacity_vehicles').update({status:on?'Reservert':'Ledig',reserved_by:on?session.user.id:null,reserved_at:on?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',r.id).eq('status',r.status);if(error)setMessage(error.message);await loadVehicles()}
 async function remove(r){if(!confirm(`Slette ${r.registration} fra kapasitetstorget?`))return;const{error}=await supabase.from('capacity_vehicles').delete().eq('id',r.id);if(error)setMessage(error.message);else await loadVehicles()}
 async function access(id,changes){const{error}=await supabase.from('capacity_profiles').update(changes).eq('user_id',id);if(error)setMessage(error.message);else await loadProfiles()}
 if(!supabase)return <Center title="Mangler tilkobling" text="Supabase-miljøvariablene er ikke tilgjengelige i denne deployen."/>;
 if(loading)return <Center title="GNS Capacity" text="Laster sikker innlogging og kapasitet …" spin/>;
 if(!session)return <Login login={login} message={message}/>;
 if(!profile?.approved)return <Pending profile={profile} save={savePending} logout={logout} saving={saving} message={message}/>;
 const available=rows.filter(r=>r.status==='Ledig').length,oslo=rows.filter(r=>r.status==='Ledig'&&/oslo|gardermoen/i.test(r.location)).length;
 return <main><header><Brand/><nav><button className={view==='tower'?'active':''} onClick={()=>setView('tower')}>Control Tower</button><button className={view==='register'?'active':''} onClick={()=>setView('register')}>Meld inn bil</button>{admin&&<button className={view==='users'?'active':''} onClick={()=>{setView('users');loadProfiles()}}>Brukere</button>}</nav><div className="account"><span>{profile.full_name||profile.email}<small>{roleName(profile.role)}</small></span><button onClick={logout}>Logg ut</button></div></header>{message&&<div className="notice">{message}<button onClick={()=>setMessage('')}>×</button></div>}
 {view==='tower'&&<section className="wrap"><div className="hero"><div><span className="eyebrow">LIVE KAPASITET</span><h1>{staff?'Alle biler':'Mine biler'}</h1><p>{staff?'Samlet oversikt over transportørenes tilgjengelige kapasitet.':'Oversikt over bilene din bruker har meldt inn.'}</p></div><button className="primary" onClick={()=>setView('register')}>+ Meld inn bil</button></div><div className="stats"><Stat t="LEDIGE BILER" n={available} s="Totalt tilgjengelig"/><Stat t="OSLO / GARDERMOEN" n={oslo} s="Tilgjengelig nå"/><Stat t="TRANSPORTØRER" n={new Set(rows.map(r=>r.carrier)).size} s="I din oversikt"/><Stat t="REGISTRERTE BILER" n={rows.length} s="Aktive poster"/></div><div className="panel"><div className="toolbar"><div><h2>Kapasitetstorg</h2><p>Én rad per bil og registreringsnummer</p></div><input aria-label="Søk biler" placeholder="Søk reg.nr, sted, transportør, retning …" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="table"><div className="tr head"><span>Status</span><span>Transportør</span><span>Reg.nr</span><span>Sted</span><span>Tilgjengelig</span><span>Biltype</span><span>Retning</span><span>Handling</span></div>{filtered.map(r=>{const[d,t]=formatDate(r.available_at),canDelete=admin||r.owner_user_id===session.user.id;return <div className={`tr ${r.status==='Ledig'?'available':'reserved'}`} key={r.id}><span><i className={`pill ${r.status.toLowerCase()}`}>{r.status}</i></span><span><b>{r.carrier}</b><small>{r.contact}{r.phone?` · ${r.phone}`:''}</small></span><span><b>{r.registration}</b></span><span>{r.location}</span><span>{d}<small>{t}</small></span><span>{r.vehicle_type||'–'}</span><span>{r.direction||'–'}</span><span className="actions">{staff&&<button className="book" onClick={()=>reserve(r)}>{r.status==='Ledig'?'Reserver':'Frigi'}</button>}{canDelete&&<button className="iconButton" onClick={()=>remove(r)}>Slett</button>}</span></div>})}{!filtered.length&&<div className="empty">Ingen biler i denne oversikten ennå.</div>}</div></div></section>}
 {view==='register'&&<section className="formpage"><div className="formcard"><span className="eyebrow">GNS CAPACITY</span><h1>Meld inn ledig bil</h1><p>Registrer én konkret bil med registreringsnummer.</p><form onSubmit={submit}><Field label="Transportør / firma"><input required value={form.carrier} onChange={e=>setForm({...form,carrier:e.target.value})} placeholder="Firmanavn"/></Field><div className="two"><Field label="Kontaktperson"><input required value={form.contact} onChange={e=>setForm({...form,contact:e.target.value})}/></Field><Field label="Telefon"><input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field></div><div className="two"><Field label="Registreringsnummer"><input required value={form.registration} onChange={e=>setForm({...form,registration:e.target.value.toUpperCase()})} placeholder="F.eks. YN 12345"/></Field><Field label="Hvor er bilen ledig?"><input required value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></Field></div><div className="two"><Field label="Dato"><input type="date" required value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></Field><Field label="Klokkeslett"><input type="time" required value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/></Field></div><div className="two"><Field label="Biltype"><select value={form.vehicle_type} onChange={e=>setForm({...form,vehicle_type:e.target.value})}><option>Termo</option><option>Express</option><option>Standard</option><option>Sideåpning</option></select></Field><Field label="Ønsket retning"><input value={form.direction} onChange={e=>setForm({...form,direction:e.target.value})}/></Field></div><Field label="Kommentar"><textarea value={form.comment} onChange={e=>setForm({...form,comment:e.target.value})} placeholder="Valgfritt"/></Field><button disabled={saving} className="primary full">{saving?'Registrerer …':'Meld inn ledig bil'}</button></form></div></section>}
 {view==='thanks'&&<section className="thanks"><div><div className="check">✓</div><h1>Bilen er registrert</h1><p>GNS Cargo ser nå bilen og registreringsnummeret i Control Tower.</p><button className="primary" onClick={()=>setView('register')}>Registrer en bil til</button><button className="link" onClick={()=>setView('tower')}>Se Control Tower</button></div></section>}
 {view==='users'&&admin&&<section className="wrap users"><div className="hero"><div><span className="eyebrow">TILGANGSSTYRING</span><h1>Brukere</h1><p>Godkjenn nye brukere og velg riktig rolle.</p></div></div><div className="panel userlist">{profiles.map(p=><div className="userrow" key={p.user_id}><div><b>{p.full_name||'Navn ikke registrert'}</b><small>{p.email}{p.company?` · ${p.company}`:''}</small></div><select value={p.role} onChange={e=>access(p.user_id,{role:e.target.value})}><option value="carrier">Transportør</option><option value="dispatcher">Dispatcher</option><option value="admin">Admin</option></select><button className={p.approved?'dangerButton':'approveButton'} onClick={()=>access(p.user_id,{approved:!p.approved})}>{p.approved?'Trekk tilgang':'Godkjenn'}</button></div>)}</div></section>}<footer>GNS CARGO AS · CAPACITY CONTROL TOWER</footer></main>
}
const Brand=()=> <div className="brand"><div className="mark">GNS</div><div><b>GNS CARGO AS</b><small>CAPACITY CONTROL TOWER</small></div></div>;
const Stat=({t,n,s})=><article><span>{t}</span><strong>{n}</strong><small>{s}</small></article>;
const Field=({label,children})=><label>{label}{children}</label>;
const Center=({title,text,spin})=><main className="authpage"><div className="authcard"><Brand/>{spin&&<div className="spinner"/>}<h1>{title}</h1><p>{text}</p></div></main>;
const Login=({login,message})=><main className="authpage"><div className="authcard"><Brand/><span className="eyebrow">SIKKER INNLOGGING</span><h1>Velkommen til GNS Capacity</h1><p>Logg inn med Microsoft-kontoen din. Nye transportører må godkjennes av GNS før de får tilgang.</p>{message&&<div className="formerror">{message}</div>}<button className="microsoft" onClick={login}><i><span/><span/><span/><span/></i>Logg inn med Microsoft</button><small className="secure">Tilgangen styres av GNS Cargo AS</small></div></main>;
const Pending=({profile,save,logout,saving,message})=><main className="authpage"><div className="authcard pending"><Brand/><span className="eyebrow">VENTER PÅ GODKJENNING</span><h1>Fullfør brukerprofilen</h1><p>GNS må godkjenne kontoen før kapasitetstorget åpnes.</p>{message&&<div className="formnotice">{message}</div>}<form onSubmit={save}><Field label="Navn"><input name="full_name" required defaultValue={profile?.full_name||''}/></Field><Field label="Transportfirma"><input name="company" required defaultValue={profile?.company||''} placeholder="Firmanavn"/></Field><button disabled={saving} className="primary full">{saving?'Lagrer …':'Lagre opplysninger'}</button></form><button className="link" onClick={logout}>Logg ut</button></div></main>;
