// Norwegian, English, German, French, Danish, Swedish, Dutch.
export const userRows = `
Bare admin kan slette andre brukere uten tilgang.|Only admins can remove other users without access.|Nur Administratoren können andere Benutzer ohne Zugriff entfernen.|Seuls les administrateurs peuvent supprimer d’autres utilisateurs sans accès.|Kun admin kan slette andre brugere uden adgang.|Endast admin kan ta bort andra användare utan åtkomst.|Alleen beheerders kunnen andere gebruikers zonder toegang verwijderen.
Brukeren er allerede slettet eller har fått tilgang. Oppdater oversikten.|The user has already been removed or granted access. Refresh the list.|Der Benutzer wurde bereits entfernt oder freigeschaltet. Aktualisieren Sie die Übersicht.|L’utilisateur a déjà été supprimé ou son accès a été accordé. Actualisez la liste.|Brugeren er allerede slettet eller har fået adgang. Opdater oversigten.|Användaren har redan tagits bort eller fått åtkomst. Uppdatera översikten.|De gebruiker is al verwijderd of heeft toegang gekregen. Vernieuw het overzicht.
Brukeren eller forespørselen er slettet fra oversikten. Historikken er beholdt.|The user or request has been removed from the list. History has been retained.|Der Benutzer oder die Anfrage wurde aus der Übersicht entfernt. Der Verlauf bleibt erhalten.|L’utilisateur ou la demande a été supprimé de la liste. L’historique est conservé.|Brugeren eller anmodningen er slettet fra oversigten. Historikken er bevaret.|Användaren eller förfrågan har tagits bort från översikten. Historiken har bevarats.|De gebruiker of aanvraag is uit het overzicht verwijderd. De geschiedenis is bewaard.
Du kan slette forespørsler og brukere uten tilgang. Trekk tilgangen før du sletter en aktiv bruker.|You can remove requests and users without access. Revoke access before removing an active user.|Sie können Anfragen und Benutzer ohne Zugriff entfernen. Entziehen Sie aktiven Benutzern zuerst den Zugriff.|Vous pouvez supprimer les demandes et les utilisateurs sans accès. Retirez l’accès avant de supprimer un utilisateur actif.|Du kan slette anmodninger og brugere uden adgang. Tilbagekald adgangen, før du sletter en aktiv bruger.|Du kan ta bort förfrågningar och användare utan åtkomst. Återkalla åtkomsten innan du tar bort en aktiv användare.|U kunt aanvragen en gebruikers zonder toegang verwijderen. Trek eerst de toegang van een actieve gebruiker in.
Aktiv tilgang|Active access|Aktiver Zugriff|Accès actif|Aktiv adgang|Aktiv åtkomst|Actieve toegang
Uten tilgang|No access|Kein Zugriff|Sans accès|Ingen adgang|Ingen åtkomst|Geen toegang
Rolle for {name}|Role for {name}|Rolle für {name}|Rôle de {name}|Rolle for {name}|Roll för {name}|Rol voor {name}
Slett {name}|Remove {name}|{name} entfernen|Supprimer {name}|Slet {name}|Ta bort {name}|{name} verwijderen
Ingen brukere i oversikten.|No users in the list.|Keine Benutzer in der Übersicht.|Aucun utilisateur dans la liste.|Ingen brugere i oversigten.|Inga användare i översikten.|Geen gebruikers in het overzicht.
Slett bruker eller forespørsel|Remove user or request|Benutzer oder Anfrage entfernen|Supprimer l’utilisateur ou la demande|Slet bruger eller anmodning|Ta bort användare eller förfrågan|Gebruiker of aanvraag verwijderen
Slette {name} fra brukeroversikten?|Remove {name} from the user list?|{name} aus der Benutzerübersicht entfernen?|Supprimer {name} de la liste des utilisateurs ?|Slet {name} fra brugeroversigten?|Ta bort {name} från användaröversikten?|{name} uit het gebruikersoverzicht verwijderen?
Brukeren fjernes fra oversikten. Bil-, lass- og reservasjonshistorikk beholdes. Brukeren får ikke tilgang ved å logge inn igjen.|The user is removed from the list. Vehicle, load and reservation history is retained. Signing in again will not restore access.|Der Benutzer wird aus der Übersicht entfernt. Fahrzeug-, Ladungs- und Reservierungsverlauf bleiben erhalten. Eine erneute Anmeldung stellt den Zugriff nicht wieder her.|L’utilisateur est retiré de la liste. L’historique des véhicules, chargements et réservations est conservé. Une nouvelle connexion ne rétablit pas l’accès.|Brugeren fjernes fra oversigten. Bil-, læs- og reservationshistorik bevares. Brugeren får ikke adgang ved at logge ind igen.|Användaren tas bort från översikten. Fordons-, last- och reservationshistorik bevaras. En ny inloggning återställer inte åtkomsten.|De gebruiker wordt uit het overzicht verwijderd. De voertuig-, lading- en reserveringsgeschiedenis blijft bewaard. Opnieuw inloggen herstelt de toegang niet.
Sletter …|Removing …|Wird entfernt …|Suppression …|Sletter …|Tar bort …|Verwijderen …
Tilgangen er fjernet|Access removed|Zugriff entfernt|Accès supprimé|Adgangen er fjernet|Åtkomsten har tagits bort|Toegang verwijderd
GNS har slettet brukerforespørselen eller fjernet brukeren fra Capacity. Kontakt GNS dersom du trenger tilgang.|GNS has removed the access request or user from Capacity. Contact GNS if you need access.|GNS hat die Zugriffsanfrage oder den Benutzer aus Capacity entfernt. Wenden Sie sich an GNS, wenn Sie Zugriff benötigen.|GNS a supprimé la demande d’accès ou l’utilisateur de Capacity. Contactez GNS pour obtenir un accès.|GNS har slettet brugeranmodningen eller fjernet brugeren fra Capacity. Kontakt GNS, hvis du har brug for adgang.|GNS har tagit bort användarförfrågan eller användaren från Capacity. Kontakta GNS om du behöver åtkomst.|GNS heeft de toegangsaanvraag of gebruiker uit Capacity verwijderd. Neem contact op met GNS als u toegang nodig hebt.
`;
